[platformio]
default_envs = esp32s3
src_dir = main

[env:esp32s3]
platform = platformio/espressif32 @ ^6.12.0
board = um_pros3
framework = espidf

board_build.partitions = partitions.csv

monitor_speed = 115200

build_flags =
    -Wno-maybe-uninitialized
    -Os

[env:esp32s3-jtag]
extends = env:esp32s3
upload_protocol = esp-builtin
